### PR TITLE
added disk-min-size per disk, ipv4-price and price update push msg 

### PR DESCRIPTION
**Pull request by Pr0mises**
New try, everything should work now as intended.

The data now gets stored as {"key":"1998135","price":"36"}; therefore a new push is also generated if the price changes for an existing server and the new price get's replaced in the hash file.

Original: 
`Well I didn't see you're working on v2 while working on this, maybe those edits could be handy for v2 as well.`
Maybe consider to use 2 spaces instead of tabs, was kinda hard to revert it :D

Added:
- disk-min-size per drive (as disk-size searches for min size for the biggest drive in the server e.g. `min-size 2000` shows server where at least one drive has 2000 GB, therefore it shows server like that: `1x 2TB HDD, 1x250GB SSD` 
and not like those: `4x 500GB SSD`)
- push msg at price change (using dict)
- deleted round in price_value and added ipv4 price for exact pricing
- You can now set your ipv4 price (default is 2.02€)
- separate msg for new price or new server

Anyway thanks for this project and maybe some changes are useful for you

### CODE REVIEW

**Comment by danielskowronski** [comment]
All those make sense - I'll try to finish v2 and merge your PR.

With the second data field, it's last call to convert the data store model from a comically long text file to a proper database - like SQLite. Will do it later :)

**Comment by danielskowronski** [comment]
Hmm, but keeping IPv4 price in code seems problematic to me. 

The IPv4 price is fixed, and you can always opt out from it (website is not suited for such dynamic tests, but you can refresh it, select "Enable IPv6 only" and re-add server to cart - price will be reduced). If you need IPv4, you'll always be adding that fixed priced to your bill, so it's not related to the server itself. 

Moreover, having different behaviour based on CLI flag that still relies on permanent data store seems very tricky to keep in sync.

**Comment by Pr0mises** [comment]
Yeah that's the problem with ipv4, I didn't even see an option to not use IPv4 even on the order page. After using "IPv6 only" the price is reduced, adding it to the basket readds the ipv4 with 2,02€ and I didn't see an option to opt it out there.

Edit: nvm was bugged.

We could prolly add: (bool) IPv6-only
Which excludes the ipv4 price. As it seems like every server is compatible with only ipv6.

**Comment by danielskowronski** [comment]
They are - you can purchase an "IPv6 only" server and later buy IPv4 addresses (or subnets up to `/24`) or cancel them anytime (in https://robot.hetzner.com/server - server - cancellation - "Cancel IPs and subnets", although at least for my servers bought before they changed IPv4 policies, I'd need to get rid of "additional" ones first).

I think they could have done a slightly better job explaining how that "IPv6 only" works. After all, they are just the same physical boxes, just without virtual resources added for free like they used to be for years.

Maybe they wanted to emphasize that hose servers with IPv4 already attached have free setup service of IPv4? As of now, there are no servers with no `IPv4` as "special" so can't say for sure. Perhaps with time we'll some of those. Still, that would be just 2-3 EUR on setup fee, there seems to be no way to find servers that previously had several IPs or subnets attached, so it does not warrant saving such info into data store.

**Comment by Pr0mises** [comment]
Well they charge 2.02€ ipv4 fee per month, that's why I wanted it to be included in the price. My older server got that additional fee as well. If you don't want to have that price included, eclude it per command

**Pull request merged**
